### ISSUE TITLE
activity 回收 无法接收回传数据。

### ISSUE THREAD

**Issue by fengfengfeng1234** [wuyr/ActivityMessenger#3]
场景环境路径：
     1.进入开发者模式 并打开不保留活动
     2. 打开 这个进行项目测试
     3.    输入  ok    start
     4.    输入  no    end

**Comment by wuyr** [comment]
同学你好，不保留活动的话，是有点难搞，可以看下这里：  <https://github.com/Ifxcyr/ActivityMessenger/issues/4>
