### ISSUE TITLE
startActivityForResult 性能

### ISSUE THREAD

**Issue by EspoirX** [wuyr/ActivityMessenger#4]
看博客，startActivityForResult 里面先移除再添加 fragment，如果连续调用N次，对性能可有影响？

**Comment by wuyr** [comment]
为什么要连续调用N次呢

**Comment by EspoirX** [comment]
确实实际中基本很少会连续调用N次，即使调用N次，连续调的概率也很低。

**Comment by EspoirX** [comment]
不过你这库里面没源码，是漏上传了？

**Comment by wuyr** [comment]
> 不过你这库里面没源码，是漏上传了？

分开仓库了，源码地址在这里：<https://github.com/ifxcyr/ActivityMessenger>
