### ISSUE TITLE
收不到数据 请问我哪里炒作有问题吗

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [wuyr/ActivityMessenger#5]
![gg](https://user-images.githubusercontent.com/25426589/100179537-3e3bfb80-2f11-11eb-83c1-6bc077572e9b.png)
![gb](https://user-images.githubusercontent.com/25426589/100179542-3ed49200-2f11-11eb-856c-887c16a467e4.png)

**Comment by wuyr** [comment]
应该是用错对象了，不应该是intent.get，如果没重命名的话，用it试试。
intent和上面的i都改为it

**Comment by TrueloveSomeGIRl** [comment]
..... 不好意思我sb 了

**Comment by fansangg** [comment]
> ..... 不好意思我sb 了

我也sb了兄弟
